package com.example.isscan.controllers;


import javafx.scene.control.Button;
import javafx.scene.control.TextArea;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class CheckAV {
    

    public Button av_button;
    public TextArea av_process, av_result;


    public String getValue() {
        if (av_process.getText().isEmpty()) {
            av_process.setPromptText("请重新输入 tasklist /svc 执行结果");
        }
        return av_process.getText();
    }


    public String getAV(String pName) {
        Map<String, String> avLists = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
        avLists.put("360tray.exe", "360安全卫士-实时保护");
        avLists.put("360safe.exe", "360安全卫士-主程序");
        avLists.put("ZhuDongFangYu.exe", "360安全卫士-主动防御");
        avLists.put("360sd.exe", "360杀毒");
        avLists.put("a2guard.exe", "a-squared杀毒");
        avLists.put("ad-watch.exe", "Lavasoft杀毒");
        avLists.put("cleaner8.exe", "The Cleaner杀毒");
        avLists.put("vba32lder.exe", "vb32杀毒");
        avLists.put("MongoosaGUI.exe", "Mongoosa杀毒");
        avLists.put("CorantiControlCenter32.exe", "Coranti2012杀毒");
        avLists.put("F-PROT.exe", "F-Prot AntiVirus");
        avLists.put("CMCTrayIcon.exe", "CMC杀毒");
        avLists.put("K7TSecurity.exe", "K7杀毒");
        avLists.put("UnThreat.exe", "UnThreat杀毒");
        avLists.put("CKSoftShiedAntivirus4.exe", "Shield Antivirus杀毒");
        avLists.put("AVWatchService.exe", "VIRUSfighter杀毒");
        avLists.put("ArcaTasksService.exe", "ArcaVir杀毒");
        avLists.put("iptray.exe", "Immunet杀毒");
        avLists.put("PSafeSysTray.exe", "PSafe杀毒");
        avLists.put("nspupsvc.exe", "nProtect杀毒");
        avLists.put("SpywareTerminatorShield.exe", "SpywareTerminator反间谍软件");
        avLists.put("BKavService.exe", "Bkav杀毒");
        avLists.put("MsMpEng.exe", "Microsoft Security Essentials");
        avLists.put("SBAMSvc.exe", "VIPRE");
        avLists.put("ccSvcHst.exe", "Norton杀毒");
        avLists.put("f-secure.exe", "冰岛");
        avLists.put("avp.exe", "Kaspersky");
        avLists.put("KvMonXP.exe", "江民杀毒");
        avLists.put("RavMonD.exe", "瑞星杀毒");
        avLists.put("Mcshield.exe", "McAfee");
        avLists.put("Tbmon.exe", "McAfee");
        avLists.put("Frameworkservice.exe", "McAfee");
        avLists.put("egui.exe", "ESET NOD32");
        avLists.put("ekrn.exe", "ESET NOD32");
        avLists.put("eguiProxy.exe", "ESET NOD32");
        avLists.put("kxetray.exe", "金山毒霸");
        avLists.put("knsdtray.exe", "可牛杀毒");
        avLists.put("TMBMSRV.exe", "趋势杀毒");
        avLists.put("avcenter.exe", "Avira(小红伞)");
        avLists.put("avguard.exe", "Avira(小红伞)");
        avLists.put("avgnt.exe", "Avira(小红伞)");
        avLists.put("sched.exe", "Avira(小红伞)");
        avLists.put("ashDisp.exe", "Avast网络安全");
        avLists.put("rtvscan.exe", "诺顿杀毒");
        avLists.put("ccapp.exe", "SymantecNorton");
        avLists.put("NPFMntor.exe", "Norton杀毒软件");
        avLists.put("ccSetMgr.exe", "赛门铁克");
        avLists.put("ccRegVfy.exe", "Norton杀毒软件");
        avLists.put("ksafe.exe", "金山卫士");
        avLists.put("QQPCRTP.exe", "QQ电脑管家");
        avLists.put("avgwdsvc.exe", "AVG杀毒");
        avLists.put("QUHLPSVC.exe", "QUICK HEAL杀毒");
        avLists.put("mssecess.exe", "微软杀毒");
        avLists.put("SavProgress.exe", "Sophos杀毒");
        avLists.put("SophosUI.exe", "Sophos杀毒");
        avLists.put("SophosFS.exe", "Sophos杀毒");
        avLists.put("SophosHealth.exe", "Sophos杀毒");
        avLists.put("SophosSafestore64.exe", "Sophos杀毒");
        avLists.put("SophosCleanM.exe", "Sophos杀毒");
        avLists.put("fsavgui.exe", "F-Secure杀毒");
        avLists.put("vsserv.exe", "比特梵德");
        avLists.put("remupd.exe", "熊猫卫士");
        avLists.put("FortiTray.exe", "飞塔");
        avLists.put("safedog.exe", "安全狗");
        avLists.put("parmor.exe", "木马克星");
        avLists.put("Iparmor.exe.exe", "木马克星");
        avLists.put("beikesan.exe", "贝壳云安全");
        avLists.put("KSWebShield.exe", "金山网盾");
        avLists.put("TrojanHunter.exe", "木马猎手");
        avLists.put("GG.exe", "巨盾网游安全盾");
        avLists.put("adam.exe", "绿鹰安全精灵");
        avLists.put("AST.exe", "超级巡警");
        avLists.put("ananwidget.exe", "墨者安全专家");
        avLists.put("AVK.exe", "AntiVirusKit");
        avLists.put("avg.exe", "AVG Anti-Virus");
        avLists.put("spidernt.exe", "Dr.web");
        avLists.put("avgaurd.exe", "Avira Antivir");
        avLists.put("vsmon.exe", "Zone Alarm");
        avLists.put("cpf.exe", "Comodo");
        avLists.put("outpost.exe", "Outpost Firewall");
        avLists.put("rfwmain.exe", "瑞星防火墙");
        avLists.put("kpfwtray.exe", "金山网镖");
        avLists.put("FYFireWall.exe", "风云防火墙");
        avLists.put("MPMon.exe", "微点主动防御");
        avLists.put("pfw.exe", "天网防火墙");
        avLists.put("BaiduSdSvc.exe", "百度杀毒-服务进程");
        avLists.put("BaiduSdTray.exe", "百度杀毒-托盘进程");
        avLists.put("BaiduSd.exe", "百度杀毒-主程序");
        avLists.put("SafeDogGuardCenter.exe", "安全狗");
        avLists.put("safedogupdatecenter.exe", "安全狗");
        avLists.put("safedogguardcenter.exe", "安全狗");
        avLists.put("SafeDogSiteIIS.exe", "安全狗");
        avLists.put("SafeDogTray.exe", "安全狗");
        avLists.put("SafeDogServerUI.exe", "安全狗");
        avLists.put("D_Safe_Manage.exe", "D盾");
        avLists.put("d_manage.exe", "D盾");
        avLists.put("yunsuo_agent_service.exe", "云锁");
        avLists.put("yunsuo_agent_daemon.exe", "云锁");
        avLists.put("HwsPanel.exe", "护卫神");
        avLists.put("hws_ui.exe", "护卫神");
        avLists.put("hws.exe", "护卫神");
        avLists.put("hwsd.exe", "护卫神");
        avLists.put("hipstray.exe", "火绒");
        avLists.put("wsctrl.exe", "火绒");
        avLists.put("usysdiag.exe", "火绒");
        avLists.put("SPHINX.exe", "SPHINX防火墙");
        avLists.put("bddownloader.exe", "百度卫士");
        avLists.put("baiduansvx.exe", "百度卫士-主进程");
        avLists.put("AvastUI.exe", "Avast!5主程序");
        avLists.put("emet_agent.exe", "EMET");
        avLists.put("emet_service.exe", "EMET");
        avLists.put("firesvc.exe", "McAfee");
        avLists.put("firetray.exe", "McAfee");
        avLists.put("hipsvc.exe", "McAfee");
        avLists.put("mfevtps.exe", "McAfee");
        avLists.put("mcafeefire.exe", "McAfee");
        avLists.put("scan32.exe", "McAfee");
        avLists.put("shstat.exe", "McAfee");
        avLists.put("vstskmgr.exe", "McAfee");
        avLists.put("engineserver.exe", "McAfee");
        avLists.put("mfeann.exe", "McAfee");
        avLists.put("mcscript.exe", "McAfee");
        avLists.put("updaterui.exe", "McAfee");
        avLists.put("udaterui.exe", "McAfee");
        avLists.put("naprdmgr.exe", "McAfee");
        avLists.put("cleanup.exe", "McAfee");
        avLists.put("cmdagent.exe", "McAfee");
        avLists.put("frminst.exe", "McAfee");
        avLists.put("mcscript_inuse.exe", "McAfee");
        avLists.put("mctray.exe", "McAfee");
        avLists.put("_avp32.exe", "卡巴斯基");
        avLists.put("_avpcc.exe", "卡巴斯基");
        avLists.put("_avpm.exe", "卡巴斯基");
        avLists.put("aAvgApi.exe", "AVG");
        avLists.put("ackwin32.exe", "已知杀软进程名称暂未收录");
        avLists.put("alertsvc.exe", "Norton AntiVirus");
        avLists.put("alogserv.exe", "McAfee VirusScan");
        avLists.put("anti-trojan.exe", "Anti-Trojan Elite");
        avLists.put("arr.exe", "Application Request Route");
        avLists.put("atguard.exe", "AntiVir");
        avLists.put("atupdater.exe", "已知杀软进程名称暂未收录");
        avLists.put("atwatch.exe", "Mustek");
        avLists.put("au.exe", "NSIS");
        avLists.put("aupdate.exe", "Symantec");
        avLists.put("auto-protect.nav80try.exe", "已知杀软进程名称暂未收录");
        avLists.put("autodown.exe", "AntiVirus AutoUpdater");
        avLists.put("avconsol.exe", "McAfee");
        avLists.put("avgcc32.exe", "AVG");
        avLists.put("avgctrl.exe", "AVG");
        avLists.put("avgemc.exe", "AVG");
        avLists.put("avgrsx.exe", "AVG");
        avLists.put("avgserv.exe", "AVG");
        avLists.put("avgserv9.exe", "AVG");
        avLists.put("avgw.exe", "AVG");
        avLists.put("avkpop.exe", "G DATA SOFTWARE AG");
        avLists.put("avkserv.exe", "G DATA SOFTWARE AG");
        avLists.put("avkservice.exe", "G DATA SOFTWARE AG");
        avLists.put("avkwctl9.exe", "G DATA SOFTWARE AG");
        avLists.put("avltmain.exe", "Panda Software Aplication");
        avLists.put("avnt.exe", "H+BEDV Datentechnik GmbH");
        avLists.put("avp32.exe", "Kaspersky Anti-Virus");
        avLists.put("avpcc.exe", " Kaspersky AntiVirus");
        avLists.put("avpdos32.exe", " Kaspersky AntiVirus");
        avLists.put("avpm.exe", " Kaspersky AntiVirus");
        avLists.put("avptc32.exe", " Kaspersky AntiVirus");
        avLists.put("avpupd.exe", " Kaspersky AntiVirus");
        avLists.put("avsynmgr.exe", "McAfee");
        avLists.put("avwin.exe", " H+BEDV");
        avLists.put("bargains.exe", "Exact Advertising SpyWare");
        avLists.put("beagle.exe", "Avast");
        avLists.put("blackd.exe", "BlackICE");
        avLists.put("blackice.exe", "BlackICE");
        avLists.put("blink.exe", "micromedia");
        avLists.put("blss.exe", "CBlaster");
        avLists.put("bootwarn.exe", "Symantec");
        avLists.put("bpc.exe", "Grokster");
        avLists.put("brasil.exe", "Exact Advertising");
        avLists.put("ccevtmgr.exe", "Norton Internet Security");
        avLists.put("cdp.exe", "CyberLink Corp.");
        avLists.put("cfd.exe", "Motive Communications");
        avLists.put("cfgwiz.exe", " Norton AntiVirus");
        avLists.put("claw95.exe", "已知杀软进程名称暂未收录");
        avLists.put("claw95cf.exe", "已知杀软进程名称暂未收录");
        avLists.put("clean.exe", "windows流氓软件清理大师");
        avLists.put("cleaner.exe", "windows流氓软件清理大师");
        avLists.put("cleaner3.exe", "windows流氓软件清理大师");
        avLists.put("cleanpc.exe", "windows流氓软件清理大师");
        avLists.put("cpd.exe", "McAfee");
        avLists.put("ctrl.exe", "已知杀软进程名称暂未收录");
        avLists.put("cv.exe", "已知杀软进程名称暂未收录");
        avLists.put("defalert.exe", "Symantec");
        avLists.put("defscangui.exe", "Symantec");
        avLists.put("defwatch.exe", "Norton Antivirus");
        avLists.put("doors.exe", "已知杀软进程名称暂未收录");
        avLists.put("dpf.exe", "已知杀软进程名称暂未收录");
        avLists.put("dpps2.exe", "PanicWare");
        avLists.put("dssagent.exe", "Broderbund");
        avLists.put("ecengine.exe", "已知杀软进程名称暂未收录");
        avLists.put("emsw.exe", "Alset Inc");
        avLists.put("ent.exe", "已知杀软进程名称暂未收录");
        avLists.put("espwatch.exe", "已知杀软进程名称暂未收录");
        avLists.put("ethereal.exe", "RationalClearCase");
        avLists.put("exe.avxw.exe", "已知杀软进程名称暂未收录");
        avLists.put("expert.exe", "已知杀软进程名称暂未收录");
        avLists.put("f-prot95.exe", "已知杀软进程名称暂未收录");
        avLists.put("fameh32.exe", "F-Secure");
        avLists.put("fast.exe", " FastUsr");
        avLists.put("fch32.exe", "F-Secure");
        avLists.put("fih32.exe", "F-Secure");
        avLists.put("findviru.exe", "F-Secure");
        avLists.put("firewall.exe", "AshampooSoftware");
        avLists.put("fnrb32.exe", "F-Secure");
        avLists.put("fp-win.exe", " F-Prot Antivirus OnDemand");
        avLists.put("fsaa.exe", "F-Secure");
        avLists.put("fsav.exe", "F-Secure");
        avLists.put("fsav32.exe", "F-Secure");
        avLists.put("fsav530stbyb.exe", "F-Secure");
        avLists.put("fsav530wtbyb.exe", "F-Secure");
        avLists.put("fsav95.exe", "F-Secure");
        avLists.put("fsgk32.exe", "F-Secure");
        avLists.put("fsm32.exe", "F-Secure");
        avLists.put("fsma32.exe", "F-Secure");
        avLists.put("fsmb32.exe", "F-Secure");
        avLists.put("gbmenu.exe", "已知杀软进程名称暂未收录");
        avLists.put("guard.exe", "ewido");
        avLists.put("guarddog.exe", "ewido");
        avLists.put("htlog.exe", "已知杀软进程名称暂未收录");
        avLists.put("htpatch.exe", "Silicon Integrated Systems Corporation");
        avLists.put("hwpe.exe", "已知杀软进程名称暂未收录");
        avLists.put("iamapp.exe", "Symantec");
        avLists.put("iamserv.exe", "Symantec");
        avLists.put("iamstats.exe", "Symantec");
        avLists.put("iedriver.exe", " Urlblaze.com");
        avLists.put("iface.exe", "Panda Antivirus Module");
        avLists.put("infus.exe", "Infus Dialer");
        avLists.put("infwin.exe", "Msviewparasite");
        avLists.put("intdel.exe", "Inet Delivery");
        avLists.put("intren.exe", "已知杀软进程名称暂未收录");
        avLists.put("jammer.exe", "已知杀软进程名称暂未收录");
        avLists.put("kavpf.exe", "Kapersky");
        avLists.put("kazza.exe", "Kapersky");
        avLists.put("keenvalue.exe", "EUNIVERSE INC");
        avLists.put("launcher.exe", "Intercort Systems");
        avLists.put("ldpro.exe", "已知杀软进程名称暂未收录");
        avLists.put("ldscan.exe", "Windows Trojans Inspector");
        avLists.put("localnet.exe", "已知杀软进程名称暂未收录");
        avLists.put("luall.exe", "Symantec");
        avLists.put("luau.exe", "Symantec");
        avLists.put("lucomserver.exe", "Norton");
        avLists.put("mcagent.exe", "McAfee");
        avLists.put("mcmnhdlr.exe", "McAfee");
        avLists.put("mctool.exe", "McAfee");
        avLists.put("mcupdate.exe", "McAfee");
        avLists.put("mcvsrte.exe", "McAfee");
        avLists.put("mcvsshld.exe", "McAfee");
        avLists.put("mfin32.exe", "MyFreeInternetUpdate");
        avLists.put("mfw2en.exe", "MyFreeInternetUpdate");
        avLists.put("mfweng3.02d30.exe", "MyFreeInternetUpdate");
        avLists.put("mgavrtcl.exe", "McAfee");
        avLists.put("mgavrte.exe", "McAfee");
        avLists.put("mghtml.exe", "McAfee");
        avLists.put("mgui.exe", "BullGuard");
        avLists.put("minilog.exe", "Zone Labs Inc");
        avLists.put("mmod.exe", "EzulaInc");
        avLists.put("mostat.exe", "WurldMediaInc");
        avLists.put("mpfagent.exe", "McAfee");
        avLists.put("mpfservice.exe", "McAfee");
        avLists.put("mpftray.exe", "McAfee");
        avLists.put("mscache.exe", "Integrated Search Technologies Spyware");
        avLists.put("mscman.exe", "OdysseusMarketingInc");
        avLists.put("msmgt.exe", "Total Velocity Spyware");
        avLists.put("msvxd.exe", "W32/Datom-A");
        avLists.put("mwatch.exe", "已知杀软进程名称暂未收录");
        avLists.put("nav.exe", "Reuters Limited");
        avLists.put("navapsvc.exe", "Norton AntiVirus");
        avLists.put("navapw32.exe", "Norton AntiVirus");
        avLists.put("navw32.exe", "Norton Antivirus");
        avLists.put("ndd32.exe", "诺顿磁盘医生");
        avLists.put("neowatchlog.exe", "已知杀软进程名称暂未收录");
        avLists.put("netutils.exe", "已知杀软进程名称暂未收录");
        avLists.put("nisserv.exe", "Norton");
        avLists.put("nisum.exe", "Norton");
        avLists.put("nmain.exe", "Norton");
        avLists.put("nod32.exe", "ESET Smart Security");
        avLists.put("norton_internet_secu_3.0_407.exe", "已知杀软进程名称暂未收录");
        avLists.put("notstart.exe", "已知杀软进程名称暂未收录");
        avLists.put("nprotect.exe", "Symantec");
        avLists.put("npscheck.exe", "Norton");
        avLists.put("npssvc.exe", "Norton");
        avLists.put("ntrtscan.exe", "趋势反病毒应用程序");
        avLists.put("nui.exe", "已知杀软进程名称暂未收录");
        avLists.put("otfix.exe", "已知杀软进程名称暂未收录");
        avLists.put("outpostinstall.exe", "Outpost");
        avLists.put("patch.exe", "趋势科技");
        avLists.put("pavw.exe", "已知杀软进程名称暂未收录");
        avLists.put("pcscan.exe", "趋势科技");
        avLists.put("pdsetup.exe", "已知杀软进程名称暂未收录");
        avLists.put("persfw.exe", "Tiny Personal Firewall");
        avLists.put("pgmonitr.exe", "PromulGate SpyWare");
        avLists.put("pingscan.exe", "已知杀软进程名称暂未收录");
        avLists.put("platin.exe", "已知杀软进程名称暂未收录");
        avLists.put("pop3trap.exe", "PC-cillin");
        avLists.put("poproxy.exe", "NortonAntiVirus");
        avLists.put("popscan.exe", "已知杀软进程名称暂未收录");
        avLists.put("powerscan.exe", "Integrated Search Technologies");
        avLists.put("ppinupdt.exe", "已知杀软进程名称暂未收录");
        avLists.put("pptbc.exe", "已知杀软进程名称暂未收录");
        avLists.put("ppvstop.exe", "已知杀软进程名称暂未收录");
        avLists.put("prizesurfer.exe", "Prizesurfer");
        avLists.put("prmt.exe", "OpiStat");
        avLists.put("prmvr.exe", "Adtomi");
        avLists.put("processmonitor.exe", "Sysinternals");
        avLists.put("proport.exe", "已知杀软进程名称暂未收录");
        avLists.put("protectx.exe", "ProtectX");
        avLists.put("pspf.exe", "已知杀软进程名称暂未收录");
        avLists.put("purge.exe", "已知杀软进程名称暂未收录");
        avLists.put("qconsole.exe", "Norton AntiVirus Quarantine Console");
        avLists.put("qserver.exe", "Norton Internet Security");
        avLists.put("rapapp.exe", "BlackICE");
        avLists.put("rb32.exe", "RapidBlaster");
        avLists.put("rcsync.exe", "PrizeSurfer");
        avLists.put("realmon.exe", "Realmon ");
        avLists.put("rescue.exe", "已知杀软进程名称暂未收录");
        avLists.put("rescue32.exe", "卡巴斯基互联网安全套装");
        avLists.put("rshell.exe", "已知杀软进程名称暂未收录");
        avLists.put("rtvscn95.exe", "Real-time virus scanner ");
        avLists.put("rulaunch.exe", "McAfee User Interface");
        avLists.put("run32dll.exe", "PAL PC Spy");
        avLists.put("safeweb.exe", "PSafe Tecnologia");
        avLists.put("sbserv.exe", "Norton Antivirus");
        avLists.put("scrscan.exe", "360杀毒");
        avLists.put("sfc.exe", "System file checker");
        avLists.put("sh.exe", "MKS Toolkit for Win3");
        avLists.put("showbehind.exe", "MicroSmarts Enterprise Component ");
        avLists.put("soap.exe", "System Soap Pro");
        avLists.put("sofi.exe", "已知杀软进程名称暂未收录");
        avLists.put("sperm.exe", "已知杀软进程名称暂未收录");
        avLists.put("supporter5.exe", "eScorcher反病毒");
        avLists.put("symproxysvc.exe", "Symantec");
        avLists.put("symtray.exe", "Symantec");
        avLists.put("tbscan.exe", "ThunderBYTE");
        avLists.put("tc.exe", "TimeCalende");
        avLists.put("titanin.exe", "TitanHide");
        avLists.put("tvmd.exe", "Total Velocity");
        avLists.put("tvtmd.exe", " Total Velocity");
        avLists.put("vettray.exe", "eTrust");
        avLists.put("vir-help.exe", "已知杀软进程名称暂未收录");
        avLists.put("vnpc3000.exe", "已知杀软进程名称暂未收录");
        avLists.put("vpc32.exe", "Symantec");
        avLists.put("vpc42.exe", "Symantec");
        avLists.put("vshwin32.exe", "McAfee");
        avLists.put("vsmain.exe", "McAfee");
        avLists.put("vsstat.exe", "McAfee");
        avLists.put("wfindv32.exe", "已知杀软进程名称暂未收录");
        avLists.put("zapro.exe", "Zone Alarm");
        avLists.put("zonealarm.exe", "Zone Alarm");
        avLists.put("AVPM.exe", "Kaspersky");
        avLists.put("A2CMD.exe", "Emsisoft Anti-Malware");
        avLists.put("A2SERVICE.exe", "a-squared free");
        avLists.put("A2FREE.exe", "a-squared Free");
        avLists.put("ADVCHK.exe", "Norton AntiVirus");
        avLists.put("AGB.exe", "安天防线");
        avLists.put("AHPROCMONSERVER.exe", "安天防线");
        avLists.put("AIRDEFENSE.exe", "AirDefense");
        avLists.put("ALERTSVC.exe", "Norton AntiVirus");
        avLists.put("AVIRA.exe", "小红伞杀毒");
        avLists.put("AMON.exe", "Tiny Personal Firewall");
        avLists.put("AVZ.exe", "AVZ");
        avLists.put("ANTIVIR.exe", "已知杀软进程名称暂未收录");
        avLists.put("APVXDWIN.exe", "熊猫卫士");
        avLists.put("ASHMAISV.exe", "Alwil");
        avLists.put("ASHSERV.exe", "Avast Anti-virus");
        avLists.put("ASHSIMPL.exe", "AVAST!VirusCleaner");
        avLists.put("ASHWEBSV.exe", "Avast");
        avLists.put("ASWUPDSV.exe", "Avast");
        avLists.put("ASWSCAN.exe", "Avast");
        avLists.put("AVCIMAN.exe", "熊猫卫士");
        avLists.put("AVCONSOL.exe", "McAfee");
        avLists.put("AVENGINE.exe", "熊猫卫士");
        avLists.put("AVESVC.exe", "Avira AntiVir Security Service");
        avLists.put("AVEVL32.exe", "已知杀软进程名称暂未收录");
        avLists.put("AVGAM.exe", "AVG");
        avLists.put("AVGCC.exe", "AVG");
        avLists.put("AVGCHSVX.exe", "AVG");
        avLists.put("AVGCSRVX", "AVG");
        avLists.put("AVGNSX.exe", "AVG");
        avLists.put("AVGCC32.exe", "AVG");
        avLists.put("AVGCTRL.exe", "AVG");
        avLists.put("AVGEMC.exe", "AVG");
        avLists.put("AVGFWSRV.exe", "AVG");
        avLists.put("AVGNTMGR.exe", "AVG");
        avLists.put("AVGSERV.exe", "AVG");
        avLists.put("AVGTRAY.exe", "AVG");
        avLists.put("AVGUPSVC.exe", "AVG");
        avLists.put("AVINITNT.exe", "Command AntiVirus for NT Server");
        avLists.put("AVPCC.exe", "Kaspersky");
        avLists.put("AVSERVER.exe", "Kerio MailServer");
        avLists.put("AVSCHED32.exe", "H+BEDV");
        avLists.put("AVSYNMGR.exe", "McAfee");
        avLists.put("AVWUPSRV.exe", "H+BEDV");
        avLists.put("BDSWITCH.exe", "BitDefender Module");
        avLists.put("BLACKD.exe", "BlackICE");
        avLists.put("CCEVTMGR.exe", "Symantec");
        avLists.put("CFP.exe", "COMODO");
        avLists.put("CLAMWIN.exe", "ClamWin Portable");
        avLists.put("CUREIT.exe", "DrWeb CureIT");
        avLists.put("DEFWATCH.exe", "Norton Antivirus");
        avLists.put("DRWADINS.exe", "Dr.Web");
        avLists.put("DRWEB.exe", "Dr.Web");
        avLists.put("DEFENDERDAEMON.exe", "ShadowDefender");
        avLists.put("EWIDOCTRL.exe", "Ewido Security Suite");
        avLists.put("EZANTIVIRUSREGISTRATIONCHECK.exe", "e-Trust Antivirus");
        avLists.put("FIREWALL.exe", "AshampooSoftware");
        avLists.put("FPROTTRAY.exe", "F-PROT Antivirus");
        avLists.put("FPWIN.exe", "Verizon");
        avLists.put("FRESHCLAM.exe", "ClamAV");
        avLists.put("FSAV32.exe", "F-Secure");
        avLists.put("FSBWSYS.exe", "F-secure");
        avLists.put("FSDFWD.exe", "F-Secure");
        avLists.put("FSGK32.exe", "F-Secure");
        avLists.put("FSGK32ST.exe", "F-Secure");
        avLists.put("FSMA32.exe", "F-Secure");
        avLists.put("FSMB32.exe", "F-Secure");
        avLists.put("FSSM32.exe", "F-Secure");
        avLists.put("GUARDGUI.exe", "网游保镖");
        avLists.put("GUARDNT.exe", "IKARUS");
        avLists.put("IAMAPP.exe", "Symantec");
        avLists.put("INOCIT.exe", "eTrust");
        avLists.put("INORPC.exe", "eTrust");
        avLists.put("INORT.exe", "eTrust");
        avLists.put("INOTASK.exe", "eTrust");
        avLists.put("INOUPTNG.exe", "eTrust");
        avLists.put("ISAFE.exe", "eTrust");
        avLists.put("KAV.exe", "Kaspersky");
        avLists.put("KAVMM.exe", "Kaspersky");
        avLists.put("KAVPF.exe", "Kaspersky");
        avLists.put("KAVPFW.exe", "Kaspersky");
        avLists.put("KAVSTART.exe", "Kaspersky");
        avLists.put("KAVSVC.exe", "Kaspersky");
        avLists.put("KAVSVCUI.exe", "Kaspersky");
        avLists.put("KMAILMON.exe", "金山毒霸");
        avLists.put("MCAGENT.exe", "McAfee");
        avLists.put("MCMNHDLR.exe", "McAfee");
        avLists.put("MCREGWIZ.exe", "McAfee");
        avLists.put("MCUPDATE.exe", "McAfee");
        avLists.put("MCVSSHLD.exe", "McAfee");
        avLists.put("MINILOG.exe", "Zone Alarm");
        avLists.put("MYAGTSVC.exe", "McAfee");
        avLists.put("MYAGTTRY.exe", "McAfee");
        avLists.put("NAVAPSVC.exe", "Norton");
        avLists.put("NAVAPW32.exe", "Norton");
        avLists.put("NAVLU32.exe", "Norton");
        avLists.put("NAVW32.exe", "Norton Antivirus");
        avLists.put("NEOWATCHLOG.exe", "NeoWatch");
        avLists.put("NEOWATCHTRAY.exe", "NeoWatch");
        avLists.put("NISSERV.exe", "Norton");
        avLists.put("NISUM.exe", "Norton");
        avLists.put("NMAIN.exe", "Norton");
        avLists.put("NOD32.exe", "ESET NOD32");
        avLists.put("NPFMSG.exe", "Norman个人防火墙");
        avLists.put("NPROTECT.exe", "Symantec");
        avLists.put("NSMDTR.exe", "Norton");
        avLists.put("NTRTSCAN.exe", "趋势科技");
        avLists.put("OFCPFWSVC.exe", "OfficeScanNT");
        avLists.put("ONLINENT.exe", "已知杀软进程名称暂未收录");
        avLists.put("OP_MON.exe", " OutpostFirewall");
        avLists.put("PAVFIRES.exe", "熊猫卫士");
        avLists.put("PAVFNSVR.exe", "熊猫卫士");
        avLists.put("PAVKRE.exe", "熊猫卫士");
        avLists.put("PAVPROT.exe", "熊猫卫士");
        avLists.put("PAVPROXY.exe", "熊猫卫士");
        avLists.put("PAVPRSRV.exe", "熊猫卫士");
        avLists.put("PAVSRV51.exe", "熊猫卫士");
        avLists.put("PAVSS.exe", "熊猫卫士");
        avLists.put("PCCGUIDE.exe", "PC-cillin");
        avLists.put("PCCIOMON.exe", "PC-cillin");
        avLists.put("PCCNTMON.exe", "PC-cillin");
        avLists.put("PCCPFW.exe", "趋势科技");
        avLists.put("PCCTLCOM.exe", "趋势科技");
        avLists.put("PCTAV.exe", "PC Tools AntiVirus");
        avLists.put("PERSFW.exe", "Tiny Personal Firewall");
        avLists.put("PERVAC.exe", "已知杀软进程名称暂未收录");
        avLists.put("PESTPATROL.exe", "Ikarus");
        avLists.put("PREVSRV.exe", "熊猫卫士");
        avLists.put("RTVSCN95.exe", "Real-time Virus Scanner");
        avLists.put("SAVADMINSERVICE.exe", "SAV");
        avLists.put("SAVMAIN.exe", "SAV");
        avLists.put("SAVSCAN.exe", "SAV");
        avLists.put("SDHELP.exe", "Spyware Doctor");
        avLists.put("SHSTAT.exe", "McAfee");
        avLists.put("SPBBCSVC.exe", "Symantec");
        avLists.put("SPIDERCPL.exe", "Dr.Web");
        avLists.put("SPIDERML.exe", "Dr.Web");
        avLists.put("SPIDERUI.exe", "Dr.Web");
        avLists.put("SPYBOTSD.exe", "Spybot ");
        avLists.put("SWAGENT.exe", "SonicWALL");
        avLists.put("SWDOCTOR.exe", "SonicWALL");
        avLists.put("SWNETSUP.exe", "Sophos");
        avLists.put("SYMLCSVC.exe", "Symantec");
        avLists.put("SYMPROXYSVC.exe", "Symantec");
        avLists.put("SYMSPORT.exe", "Sysmantec");
        avLists.put("SYMWSC.exe", "Sysmantec");
        avLists.put("SYNMGR.exe", "Sysmantec");
        avLists.put("TMLISTEN.exe", "趋势科技");
        avLists.put("TMNTSRV.exe", "趋势科技");
        avLists.put("TMPROXY.exe", "趋势科技");
        avLists.put("TNBUTIL.exe", "Anti-Virus");
        avLists.put("VBA32ECM.exe", "已知杀软进程名称暂未收录");
        avLists.put("VBA32IFS.exe", "已知杀软进程名称暂未收录");
        avLists.put("VBA32PP3.exe", "已知杀软进程名称暂未收录");
        avLists.put("VCRMON.exe", "VirusChaser");
        avLists.put("VRMONNT.exe", "HAURI");
        avLists.put("VRMONSVC.exe", "HAURI");
        avLists.put("VSHWIN32.exe", "McAfee");
        avLists.put("VSSTAT.exe", "McAfee");
        avLists.put("XCOMMSVR.exe", "BitDefender");
        avLists.put("ZONEALARM.exe", "Zone Alarm");
        avLists.put("360rp.exe", "360杀毒");
        avLists.put("afwServ.exe", " Avast Antivirus ");
        avLists.put("safeboxTray.exe", "360杀毒");
        avLists.put("360safebox.exe", "360杀毒");
        avLists.put("QQPCTray.exe", "QQ电脑管家");
        avLists.put("KSafeTray.exe", "金山毒霸");
        avLists.put("KSafeSvc.exe", "金山毒霸");
        avLists.put("KWatch.exe", "金山毒霸");
        avLists.put("gov_defence_service.exe", "云锁");
        avLists.put("gov_defence_daemon.exe", "云锁");
        avLists.put("smartscreen.exe", "Windows Defender");

        if (avLists.containsKey(pName)){
            return avLists.get(pName);
        }
        return "";
    }

    public void CheckAVRun() {
       String regex = "\\w+\\.exe";
       Pattern pattern = Pattern.compile(regex);
       Matcher m = pattern.matcher(getValue());
       while (m.find()){
           String pName = m.group();
           String result = getAV(pName);
           if (result.length() != 0) {
               av_result.appendText(pName + "==> " + result + "\n");
           }
       }
    }
}

